spring.application.name=workflow_builder



spring.data.mongodb.uri=mongodb://localhost:27017/workflow_builder

jwt.secret=U29tZVN1cGVyU2VjdXJlU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMw==

jwt.expiration=86400000   
server.port=8080
logging.level.org.springframework.security=DEBUG
